### ISSUE TITLE
Installation errors in AI 2015.2.1 Mac

### ISSUE THREAD

**Issue by fallenartist** [yasashiku/hanpuku#1]
Firstly, let me tell you this extension is such a great find! Is it still in development?

Unfortunately I can't seem to install it on AI 19.2.1 / OS X El Capitan. The installer gives me the following errors:

![screen shot 2016-03-17 at 09 43 44](https://cloud.githubusercontent.com/assets/661820/13842418/f6febb1e-ec25-11e5-9318-e0a1722ec8f7.png)

![screen shot 2016-03-17 at 09 47 07](https://cloud.githubusercontent.com/assets/661820/13842428/02f14414-ec26-11e5-8d93-ea61b911edcd.png)

Any ideas?

**Comment by alex-r-bigelow** [comment]
Thanks for the interest! I'm able to replicate this behavior, and I'm looking into it now—thanks for the heads up!

As far as development goes... it's research code, meaning now that we're working on the academic paper, there really isn't any funding to let me keep working on it (even though I really, really want to). I'm more than happy to fix bugs if you find them, though!

**Comment by alex-r-bigelow** [comment]
Hmm, it looks like Adobe has done something strange with extensions in one of the latest updates. I'm still not sure exactly what it is, but for now this command line workaround _should_ at least install the extension. With Illustrator closed, open the terminal and type or paste these commands:

```
cd ~/Library/Application\ Support/Adobe/
mkdir CEP
mkdir CEP/extensions
cd CEP/extensions
git clone https://github.com/alex-r-bigelow/hanpuku.git
```

If you don't have git installed on your system, you can download the [zipped source code](https://github.com/alex-r-bigelow/hanpuku/archive/master.zip), extract it, and type this instead of the last line:

```
mv ~/Downloads/hanpuku-master ~/Library/Application\ Support/Adobe/CEP/extensions/hanpuku
```

If you open Illustrator after all that, the extension should be installed (just delete the hanpuku directory to uninstall).

**Comment by alex-r-bigelow** [comment]
Sorry about the delay in getting to this. It looks like we're getting these errors because Adobe has officially killed off the Extension Manager altogether: https://www.adobeexchange.com/resources/27

For now, the workaround will have to suffice... I think the only way for a smooth installation is to get Adobe to host the extension, or I could look into making an independent installer. I'll update as soon as I figure out the best way forward.

**Comment by alex-r-bigelow** [comment]
I now have an Adobe Add-on, so I'm marking this fixed as of https://github.com/alex-r-bigelow/hanpuku/commit/37a5018977213658032b4601f5a5455d28ac94cb
